language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -r build-reqs.txt
# command to run tests
script: python -m pytest tests/
